application: thisismyagenda
version: 3
runtime: python
api_version: 1

handlers:
- url: /static/
  static_dir: static

- url: /tasks/verify
  script: main.py
  login: admin

- url: /.*
  script: main.py

inbound_services:
- xmpp_message
